# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q3yncRtzY9-fqV_3fhuSBhFRuDoupo7s
"""

import os
print(os.listdir())

import pandas as pd

df = pd.read_csv("Titanic-Dataset.csv")

df.head()

df.info()

df.isnull().sum()

df["Age"].fillna(df["Age"].mean(), inplace=True)

df["Embarked"].fillna(df["Embarked"].mode()[0], inplace=True)

df["Cabin"].fillna("Unknown", inplace=True)

df.isnull().sum()

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["Sex"] = le.fit_transform(df["Sex"])

df["Embarked"] = le.fit_transform(df["Embarked"])

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df[["Age","Fare"]] = scaler.fit_transform(df[["Age","Fare"]])

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8,4))

sns.boxplot(data=df[["Age","Fare"]])

plt.show()

Q1 = df["Fare"].quantile(0.25)

Q3 = df["Fare"].quantile(0.75)

IQR = Q3 - Q1

df = df[(df["Fare"] >= Q1 - 1.5*IQR) &
        (df["Fare"] <= Q3 + 1.5*IQR)]

df.to_csv("cleaned_titanic.csv", index=False)